/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'villageStays' : null } |
  { 'culturalImmersion' : null } |
  { 'foodTrails' : null } |
  { 'natureEco' : null };
export interface Coordinates { 'latitude' : number, 'longitude' : number }
export interface Destination {
  'id' : bigint,
  'region' : Region,
  'galleryImages' : Array<ExternalBlob>,
  'trustBreakdown' : TrustBreakdown,
  'name' : string,
  'tags' : Array<string>,
  'trustScore' : number,
  'highlights' : Array<string>,
  'heroImage' : [] | [ExternalBlob],
  'story' : string,
  'isVerified' : boolean,
  'category' : Category,
  'trustedHosts' : Array<bigint>,
}
export interface DestinationWithMedia {
  'destination' : Destination,
  'gallery' : Array<ExternalBlob>,
}
export interface ExperienceRequest {
  'id' : bigint,
  'destinationId' : bigint,
  'userPrincipal' : Principal,
  'message' : string,
}
export interface ExperienceRequestInput {
  'destinationId' : bigint,
  'message' : string,
}
export type ExternalBlob = Uint8Array;
export interface FeaturedPlacesResponse {
  'heroImages' : Array<ExternalBlob>,
  'topDestinations' : Array<DestinationWithMedia>,
}
export interface Host {
  'id' : bigint,
  'bio' : string,
  'verified' : boolean,
  'destinationId' : bigint,
  'name' : string,
  'trustIndex' : number,
  'location' : string,
}
export interface Media {
  'id' : bigint,
  'url' : ExternalBlob,
  'destinationId' : bigint,
  'name' : string,
  'mediaType' : MediaType,
}
export type MediaType = { 'story' : null } |
  { 'gallery' : null };
export interface Region {
  'country' : string,
  'cityOrVillage' : [] | [string],
  'state' : [] | [string],
  'coordinates' : [] | [Coordinates],
}
export interface StoryResponse {
  'destinationId' : bigint,
  'story' : [] | [ExternalBlob],
  'gallery' : Array<ExternalBlob>,
}
export interface TrustBreakdown {
  'communityReviews' : number,
  'hostVerification' : number,
  'safetyRatings' : number,
}
export interface UserProfileView {
  'pastExplorations' : Array<bigint>,
  'principal' : Principal,
  'displayName' : string,
  'role' : UserRole,
  'savedFavorites' : Array<bigint>,
}
export type UserRole = { 'host' : null } |
  { 'traveller' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDestination' : ActorMethod<[Destination], undefined>,
  'addHost' : ActorMethod<[Host], undefined>,
  'addMediaEntry' : ActorMethod<[Media], undefined>,
  'addPastExploration' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createUserProfile' : ActorMethod<[UserRole, string], undefined>,
  'fetchDestinationStory' : ActorMethod<[bigint], [] | [StoryResponse]>,
  'fetchFeaturedPlaces' : ActorMethod<[], FeaturedPlacesResponse>,
  'filterTrustworthyDestinations' : ActorMethod<
    [Category, number],
    Array<Destination>
  >,
  'getAllRequests' : ActorMethod<[], Array<ExperienceRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfileView]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getDestination' : ActorMethod<[bigint], [] | [Destination]>,
  'getHost' : ActorMethod<[bigint], [] | [Host]>,
  'getUserProfileView' : ActorMethod<[Principal], [] | [UserProfileView]>,
  'getUserRequests' : ActorMethod<[], Array<ExperienceRequest>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listDestinations' : ActorMethod<[], Array<Destination>>,
  'listHosts' : ActorMethod<[], Array<Host>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfileView], undefined>,
  'saveFavorite' : ActorMethod<[bigint], undefined>,
  'searchPlaces' : ActorMethod<[string, [] | [Category]], Array<Destination>>,
  'submitExperienceRequest' : ActorMethod<[ExperienceRequestInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];