/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Coordinates = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const Region = IDL.Record({
  'country' : IDL.Text,
  'cityOrVillage' : IDL.Opt(IDL.Text),
  'state' : IDL.Opt(IDL.Text),
  'coordinates' : IDL.Opt(Coordinates),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const TrustBreakdown = IDL.Record({
  'communityReviews' : IDL.Float64,
  'hostVerification' : IDL.Float64,
  'safetyRatings' : IDL.Float64,
});
export const Category = IDL.Variant({
  'villageStays' : IDL.Null,
  'culturalImmersion' : IDL.Null,
  'foodTrails' : IDL.Null,
  'natureEco' : IDL.Null,
});
export const Destination = IDL.Record({
  'id' : IDL.Nat,
  'region' : Region,
  'galleryImages' : IDL.Vec(ExternalBlob),
  'trustBreakdown' : TrustBreakdown,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'trustScore' : IDL.Float64,
  'highlights' : IDL.Vec(IDL.Text),
  'heroImage' : IDL.Opt(ExternalBlob),
  'story' : IDL.Text,
  'isVerified' : IDL.Bool,
  'category' : Category,
  'trustedHosts' : IDL.Vec(IDL.Nat),
});
export const Host = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'verified' : IDL.Bool,
  'destinationId' : IDL.Nat,
  'name' : IDL.Text,
  'trustIndex' : IDL.Float64,
  'location' : IDL.Text,
});
export const MediaType = IDL.Variant({
  'story' : IDL.Null,
  'gallery' : IDL.Null,
});
export const Media = IDL.Record({
  'id' : IDL.Nat,
  'url' : ExternalBlob,
  'destinationId' : IDL.Nat,
  'name' : IDL.Text,
  'mediaType' : MediaType,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'host' : IDL.Null,
  'traveller' : IDL.Null,
});
export const StoryResponse = IDL.Record({
  'destinationId' : IDL.Nat,
  'story' : IDL.Opt(ExternalBlob),
  'gallery' : IDL.Vec(ExternalBlob),
});
export const DestinationWithMedia = IDL.Record({
  'destination' : Destination,
  'gallery' : IDL.Vec(ExternalBlob),
});
export const FeaturedPlacesResponse = IDL.Record({
  'heroImages' : IDL.Vec(ExternalBlob),
  'topDestinations' : IDL.Vec(DestinationWithMedia),
});
export const ExperienceRequest = IDL.Record({
  'id' : IDL.Nat,
  'destinationId' : IDL.Nat,
  'userPrincipal' : IDL.Principal,
  'message' : IDL.Text,
});
export const UserProfileView = IDL.Record({
  'pastExplorations' : IDL.Vec(IDL.Nat),
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'role' : UserRole,
  'savedFavorites' : IDL.Vec(IDL.Nat),
});
export const ExperienceRequestInput = IDL.Record({
  'destinationId' : IDL.Nat,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDestination' : IDL.Func([Destination], [], []),
  'addHost' : IDL.Func([Host], [], []),
  'addMediaEntry' : IDL.Func([Media], [], []),
  'addPastExploration' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createUserProfile' : IDL.Func([UserRole, IDL.Text], [], []),
  'fetchDestinationStory' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(StoryResponse)],
      ['query'],
    ),
  'fetchFeaturedPlaces' : IDL.Func([], [FeaturedPlacesResponse], ['query']),
  'filterTrustworthyDestinations' : IDL.Func(
      [Category, IDL.Float64],
      [IDL.Vec(Destination)],
      ['query'],
    ),
  'getAllRequests' : IDL.Func([], [IDL.Vec(ExperienceRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfileView)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getDestination' : IDL.Func([IDL.Nat], [IDL.Opt(Destination)], ['query']),
  'getHost' : IDL.Func([IDL.Nat], [IDL.Opt(Host)], ['query']),
  'getUserProfileView' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfileView)],
      ['query'],
    ),
  'getUserRequests' : IDL.Func([], [IDL.Vec(ExperienceRequest)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
  'listHosts' : IDL.Func([], [IDL.Vec(Host)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfileView], [], []),
  'saveFavorite' : IDL.Func([IDL.Nat], [], []),
  'searchPlaces' : IDL.Func(
      [IDL.Text, IDL.Opt(Category)],
      [IDL.Vec(Destination)],
      ['query'],
    ),
  'submitExperienceRequest' : IDL.Func([ExperienceRequestInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Coordinates = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const Region = IDL.Record({
    'country' : IDL.Text,
    'cityOrVillage' : IDL.Opt(IDL.Text),
    'state' : IDL.Opt(IDL.Text),
    'coordinates' : IDL.Opt(Coordinates),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const TrustBreakdown = IDL.Record({
    'communityReviews' : IDL.Float64,
    'hostVerification' : IDL.Float64,
    'safetyRatings' : IDL.Float64,
  });
  const Category = IDL.Variant({
    'villageStays' : IDL.Null,
    'culturalImmersion' : IDL.Null,
    'foodTrails' : IDL.Null,
    'natureEco' : IDL.Null,
  });
  const Destination = IDL.Record({
    'id' : IDL.Nat,
    'region' : Region,
    'galleryImages' : IDL.Vec(ExternalBlob),
    'trustBreakdown' : TrustBreakdown,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'trustScore' : IDL.Float64,
    'highlights' : IDL.Vec(IDL.Text),
    'heroImage' : IDL.Opt(ExternalBlob),
    'story' : IDL.Text,
    'isVerified' : IDL.Bool,
    'category' : Category,
    'trustedHosts' : IDL.Vec(IDL.Nat),
  });
  const Host = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'verified' : IDL.Bool,
    'destinationId' : IDL.Nat,
    'name' : IDL.Text,
    'trustIndex' : IDL.Float64,
    'location' : IDL.Text,
  });
  const MediaType = IDL.Variant({ 'story' : IDL.Null, 'gallery' : IDL.Null });
  const Media = IDL.Record({
    'id' : IDL.Nat,
    'url' : ExternalBlob,
    'destinationId' : IDL.Nat,
    'name' : IDL.Text,
    'mediaType' : MediaType,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserRole = IDL.Variant({ 'host' : IDL.Null, 'traveller' : IDL.Null });
  const StoryResponse = IDL.Record({
    'destinationId' : IDL.Nat,
    'story' : IDL.Opt(ExternalBlob),
    'gallery' : IDL.Vec(ExternalBlob),
  });
  const DestinationWithMedia = IDL.Record({
    'destination' : Destination,
    'gallery' : IDL.Vec(ExternalBlob),
  });
  const FeaturedPlacesResponse = IDL.Record({
    'heroImages' : IDL.Vec(ExternalBlob),
    'topDestinations' : IDL.Vec(DestinationWithMedia),
  });
  const ExperienceRequest = IDL.Record({
    'id' : IDL.Nat,
    'destinationId' : IDL.Nat,
    'userPrincipal' : IDL.Principal,
    'message' : IDL.Text,
  });
  const UserProfileView = IDL.Record({
    'pastExplorations' : IDL.Vec(IDL.Nat),
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'role' : UserRole,
    'savedFavorites' : IDL.Vec(IDL.Nat),
  });
  const ExperienceRequestInput = IDL.Record({
    'destinationId' : IDL.Nat,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDestination' : IDL.Func([Destination], [], []),
    'addHost' : IDL.Func([Host], [], []),
    'addMediaEntry' : IDL.Func([Media], [], []),
    'addPastExploration' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createUserProfile' : IDL.Func([UserRole, IDL.Text], [], []),
    'fetchDestinationStory' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(StoryResponse)],
        ['query'],
      ),
    'fetchFeaturedPlaces' : IDL.Func([], [FeaturedPlacesResponse], ['query']),
    'filterTrustworthyDestinations' : IDL.Func(
        [Category, IDL.Float64],
        [IDL.Vec(Destination)],
        ['query'],
      ),
    'getAllRequests' : IDL.Func([], [IDL.Vec(ExperienceRequest)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfileView)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getDestination' : IDL.Func([IDL.Nat], [IDL.Opt(Destination)], ['query']),
    'getHost' : IDL.Func([IDL.Nat], [IDL.Opt(Host)], ['query']),
    'getUserProfileView' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfileView)],
        ['query'],
      ),
    'getUserRequests' : IDL.Func([], [IDL.Vec(ExperienceRequest)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
    'listHosts' : IDL.Func([], [IDL.Vec(Host)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfileView], [], []),
    'saveFavorite' : IDL.Func([IDL.Nat], [], []),
    'searchPlaces' : IDL.Func(
        [IDL.Text, IDL.Opt(Category)],
        [IDL.Vec(Destination)],
        ['query'],
      ),
    'submitExperienceRequest' : IDL.Func([ExperienceRequestInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };