/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Host {
    id: bigint;
    bio: string;
    verified: boolean;
    destinationId: bigint;
    name: string;
    trustIndex: number;
    location: string;
}
export interface Destination {
    id: bigint;
    region: Region;
    galleryImages: Array<ExternalBlob>;
    trustBreakdown: TrustBreakdown;
    name: string;
    tags: Array<string>;
    trustScore: number;
    highlights: Array<string>;
    heroImage?: ExternalBlob;
    story: string;
    isVerified: boolean;
    category: Category;
    trustedHosts: Array<bigint>;
}
export interface DestinationWithMedia {
    destination: Destination;
    gallery: Array<ExternalBlob>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Coordinates {
    latitude: number;
    longitude: number;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface FeaturedPlacesResponse {
    heroImages: Array<ExternalBlob>;
    topDestinations: Array<DestinationWithMedia>;
}
export interface Region {
    country: string;
    cityOrVillage?: string;
    state?: string;
    coordinates?: Coordinates;
}
export interface ExperienceRequestInput {
    destinationId: bigint;
    message: string;
}
export interface ExperienceRequest {
    id: bigint;
    destinationId: bigint;
    userPrincipal: Principal;
    message: string;
}
export interface StoryResponse {
    destinationId: bigint;
    story?: ExternalBlob;
    gallery: Array<ExternalBlob>;
}
export interface UserProfileView {
    pastExplorations: Array<bigint>;
    principal: Principal;
    displayName: string;
    role: UserRole;
    savedFavorites: Array<bigint>;
}
export interface Media {
    id: bigint;
    url: ExternalBlob;
    destinationId: bigint;
    name: string;
    mediaType: MediaType;
}
export interface TrustBreakdown {
    communityReviews: number;
    hostVerification: number;
    safetyRatings: number;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Category {
    villageStays = "villageStays",
    culturalImmersion = "culturalImmersion",
    foodTrails = "foodTrails",
    natureEco = "natureEco"
}
export enum MediaType {
    story = "story",
    gallery = "gallery"
}
export enum UserRole {
    host = "host",
    traveller = "traveller"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDestination(destInput: Destination): Promise<void>;
    addHost(hostInput: Host): Promise<void>;
    addMediaEntry(inputMedia: Media): Promise<void>;
    addPastExploration(destinationId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    createUserProfile(role: UserRole, displayName: string): Promise<void>;
    fetchDestinationStory(destinationId: bigint): Promise<StoryResponse | null>;
    fetchFeaturedPlaces(): Promise<FeaturedPlacesResponse>;
    filterTrustworthyDestinations(category: Category, minTrustScore: number): Promise<Array<Destination>>;
    getAllRequests(): Promise<Array<ExperienceRequest>>;
    getCallerUserProfile(): Promise<UserProfileView | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getDestination(id: bigint): Promise<Destination | null>;
    getHost(id: bigint): Promise<Host | null>;
    getUserProfileView(user: Principal): Promise<UserProfileView | null>;
    getUserRequests(): Promise<Array<ExperienceRequest>>;
    isCallerAdmin(): Promise<boolean>;
    listDestinations(): Promise<Array<Destination>>;
    listHosts(): Promise<Array<Host>>;
    saveCallerUserProfile(profile: UserProfileView): Promise<void>;
    saveFavorite(destinationId: bigint): Promise<void>;
    searchPlaces(searchTerm: string, category: Category | null): Promise<Array<Destination>>;
    submitExperienceRequest(request: ExperienceRequestInput): Promise<void>;
}
import type { Category as _Category, Coordinates as _Coordinates, Destination as _Destination, DestinationWithMedia as _DestinationWithMedia, ExternalBlob as _ExternalBlob, FeaturedPlacesResponse as _FeaturedPlacesResponse, Host as _Host, Media as _Media, MediaType as _MediaType, Region as _Region, StoryResponse as _StoryResponse, TrustBreakdown as _TrustBreakdown, UserProfileView as _UserProfileView, UserRole as _UserRole, UserRole__1 as _UserRole__1, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDestination(arg0: Destination): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDestination(await to_candid_Destination_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDestination(await to_candid_Destination_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addHost(arg0: Host): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addHost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHost(arg0);
            return result;
        }
    }
    async addMediaEntry(arg0: Media): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMediaEntry(await to_candid_Media_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMediaEntry(await to_candid_Media_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addPastExploration(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPastExploration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPastExploration(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n20(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n20(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createUserProfile(arg0: UserRole, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUserProfile(to_candid_UserRole_n22(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUserProfile(to_candid_UserRole_n22(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async fetchDestinationStory(arg0: bigint): Promise<StoryResponse | null> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchDestinationStory(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchDestinationStory(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async fetchFeaturedPlaces(): Promise<FeaturedPlacesResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchFeaturedPlaces();
                return from_candid_FeaturedPlacesResponse_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchFeaturedPlaces();
            return from_candid_FeaturedPlacesResponse_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterTrustworthyDestinations(arg0: Category, arg1: number): Promise<Array<Destination>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterTrustworthyDestinations(to_candid_Category_n14(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterTrustworthyDestinations(to_candid_Category_n14(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRequests(): Promise<Array<ExperienceRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRequests();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDestination(arg0: bigint): Promise<Destination | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDestination(arg0);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDestination(arg0);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHost(arg0: bigint): Promise<Host | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHost(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHost(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfileView(arg0: Principal): Promise<UserProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfileView(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfileView(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserRequests(): Promise<Array<ExperienceRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRequests();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listDestinations(): Promise<Array<Destination>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDestinations();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDestinations();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async listHosts(): Promise<Array<Host>> {
        if (this.processError) {
            try {
                const result = await this.actor.listHosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listHosts();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfileView): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfileView_n53(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfileView_n53(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveFavorite(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveFavorite(arg0);
            return result;
        }
    }
    async searchPlaces(arg0: string, arg1: Category | null): Promise<Array<Destination>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPlaces(arg0, to_candid_opt_n55(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPlaces(arg0, to_candid_opt_n55(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitExperienceRequest(arg0: ExperienceRequestInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitExperienceRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitExperienceRequest(arg0);
            return result;
        }
    }
}
function from_candid_Category_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
async function from_candid_DestinationWithMedia_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DestinationWithMedia): Promise<DestinationWithMedia> {
    return await from_candid_record_n34(_uploadFile, _downloadFile, value);
}
async function from_candid_Destination_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Destination): Promise<Destination> {
    return await from_candid_record_n36(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_FeaturedPlacesResponse_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeaturedPlacesResponse): Promise<FeaturedPlacesResponse> {
    return await from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Region_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Region): Region {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
async function from_candid_StoryResponse_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StoryResponse): Promise<StoryResponse> {
    return await from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfileView_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfileView): UserProfileView {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StoryResponse]): Promise<StoryResponse | null> {
    return value.length === 0 ? null : await from_candid_StoryResponse_n25(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Coordinates]): Coordinates | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfileView]): UserProfileView | null {
    return value.length === 0 ? null : from_candid_UserProfileView_n45(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Destination]): Promise<Destination | null> {
    return value.length === 0 ? null : await from_candid_Destination_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Host]): Host | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    destinationId: bigint;
    story: [] | [_ExternalBlob];
    gallery: Array<_ExternalBlob>;
}): Promise<{
    destinationId: bigint;
    story?: ExternalBlob;
    gallery: Array<ExternalBlob>;
}> {
    return {
        destinationId: value.destinationId,
        story: record_opt_to_undefined(await from_candid_opt_n27(_uploadFile, _downloadFile, value.story)),
        gallery: await from_candid_vec_n29(_uploadFile, _downloadFile, value.gallery)
    };
}
async function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    heroImages: Array<_ExternalBlob>;
    topDestinations: Array<_DestinationWithMedia>;
}): Promise<{
    heroImages: Array<ExternalBlob>;
    topDestinations: Array<DestinationWithMedia>;
}> {
    return {
        heroImages: await from_candid_vec_n29(_uploadFile, _downloadFile, value.heroImages),
        topDestinations: await from_candid_vec_n32(_uploadFile, _downloadFile, value.topDestinations)
    };
}
async function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    destination: _Destination;
    gallery: Array<_ExternalBlob>;
}): Promise<{
    destination: Destination;
    gallery: Array<ExternalBlob>;
}> {
    return {
        destination: await from_candid_Destination_n35(_uploadFile, _downloadFile, value.destination),
        gallery: await from_candid_vec_n29(_uploadFile, _downloadFile, value.gallery)
    };
}
async function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    region: _Region;
    galleryImages: Array<_ExternalBlob>;
    trustBreakdown: _TrustBreakdown;
    name: string;
    tags: Array<string>;
    trustScore: number;
    highlights: Array<string>;
    heroImage: [] | [_ExternalBlob];
    story: string;
    isVerified: boolean;
    category: _Category;
    trustedHosts: Array<bigint>;
}): Promise<{
    id: bigint;
    region: Region;
    galleryImages: Array<ExternalBlob>;
    trustBreakdown: TrustBreakdown;
    name: string;
    tags: Array<string>;
    trustScore: number;
    highlights: Array<string>;
    heroImage?: ExternalBlob;
    story: string;
    isVerified: boolean;
    category: Category;
    trustedHosts: Array<bigint>;
}> {
    return {
        id: value.id,
        region: from_candid_Region_n37(_uploadFile, _downloadFile, value.region),
        galleryImages: await from_candid_vec_n29(_uploadFile, _downloadFile, value.galleryImages),
        trustBreakdown: value.trustBreakdown,
        name: value.name,
        tags: value.tags,
        trustScore: value.trustScore,
        highlights: value.highlights,
        heroImage: record_opt_to_undefined(await from_candid_opt_n27(_uploadFile, _downloadFile, value.heroImage)),
        story: value.story,
        isVerified: value.isVerified,
        category: from_candid_Category_n41(_uploadFile, _downloadFile, value.category),
        trustedHosts: value.trustedHosts
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    country: string;
    cityOrVillage: [] | [string];
    state: [] | [string];
    coordinates: [] | [_Coordinates];
}): {
    country: string;
    cityOrVillage?: string;
    state?: string;
    coordinates?: Coordinates;
} {
    return {
        country: value.country,
        cityOrVillage: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.cityOrVillage)),
        state: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.state)),
        coordinates: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.coordinates))
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pastExplorations: Array<bigint>;
    principal: Principal;
    displayName: string;
    role: _UserRole;
    savedFavorites: Array<bigint>;
}): {
    pastExplorations: Array<bigint>;
    principal: Principal;
    displayName: string;
    role: UserRole;
    savedFavorites: Array<bigint>;
} {
    return {
        pastExplorations: value.pastExplorations,
        principal: value.principal,
        displayName: value.displayName,
        role: from_candid_UserRole_n47(_uploadFile, _downloadFile, value.role),
        savedFavorites: value.savedFavorites
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    villageStays: null;
} | {
    culturalImmersion: null;
} | {
    foodTrails: null;
} | {
    natureEco: null;
}): Category {
    return "villageStays" in value ? Category.villageStays : "culturalImmersion" in value ? Category.culturalImmersion : "foodTrails" in value ? Category.foodTrails : "natureEco" in value ? Category.natureEco : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    host: null;
} | {
    traveller: null;
}): UserRole {
    return "host" in value ? UserRole.host : "traveller" in value ? UserRole.traveller : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DestinationWithMedia>): Promise<Array<DestinationWithMedia>> {
    return await Promise.all(value.map(async (x)=>await from_candid_DestinationWithMedia_n33(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Destination>): Promise<Array<Destination>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Destination_n35(_uploadFile, _downloadFile, x)));
}
function to_candid_Category_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_Destination_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Destination): Promise<_Destination> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_MediaType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaType): _MediaType {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
async function to_candid_Media_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Media): Promise<_Media> {
    return await to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_Region_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Region): _Region {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfileView_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfileView): _UserProfileView {
    return to_candid_record_n54(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category | null): [] | [_Category] {
    return value === null ? candid_none() : candid_some(to_candid_Category_n14(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    country: string;
    cityOrVillage?: string;
    state?: string;
    coordinates?: Coordinates;
}): {
    country: string;
    cityOrVillage: [] | [string];
    state: [] | [string];
    coordinates: [] | [_Coordinates];
} {
    return {
        country: value.country,
        cityOrVillage: value.cityOrVillage ? candid_some(value.cityOrVillage) : candid_none(),
        state: value.state ? candid_some(value.state) : candid_none(),
        coordinates: value.coordinates ? candid_some(value.coordinates) : candid_none()
    };
}
async function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    url: ExternalBlob;
    destinationId: bigint;
    name: string;
    mediaType: MediaType;
}): Promise<{
    id: bigint;
    url: _ExternalBlob;
    destinationId: bigint;
    name: string;
    mediaType: _MediaType;
}> {
    return {
        id: value.id,
        url: await to_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value.url),
        destinationId: value.destinationId,
        name: value.name,
        mediaType: to_candid_MediaType_n18(_uploadFile, _downloadFile, value.mediaType)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pastExplorations: Array<bigint>;
    principal: Principal;
    displayName: string;
    role: UserRole;
    savedFavorites: Array<bigint>;
}): {
    pastExplorations: Array<bigint>;
    principal: Principal;
    displayName: string;
    role: _UserRole;
    savedFavorites: Array<bigint>;
} {
    return {
        pastExplorations: value.pastExplorations,
        principal: value.principal,
        displayName: value.displayName,
        role: to_candid_UserRole_n22(_uploadFile, _downloadFile, value.role),
        savedFavorites: value.savedFavorites
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    region: Region;
    galleryImages: Array<ExternalBlob>;
    trustBreakdown: TrustBreakdown;
    name: string;
    tags: Array<string>;
    trustScore: number;
    highlights: Array<string>;
    heroImage?: ExternalBlob;
    story: string;
    isVerified: boolean;
    category: Category;
    trustedHosts: Array<bigint>;
}): Promise<{
    id: bigint;
    region: _Region;
    galleryImages: Array<_ExternalBlob>;
    trustBreakdown: _TrustBreakdown;
    name: string;
    tags: Array<string>;
    trustScore: number;
    highlights: Array<string>;
    heroImage: [] | [_ExternalBlob];
    story: string;
    isVerified: boolean;
    category: _Category;
    trustedHosts: Array<bigint>;
}> {
    return {
        id: value.id,
        region: to_candid_Region_n10(_uploadFile, _downloadFile, value.region),
        galleryImages: await to_candid_vec_n12(_uploadFile, _downloadFile, value.galleryImages),
        trustBreakdown: value.trustBreakdown,
        name: value.name,
        tags: value.tags,
        trustScore: value.trustScore,
        highlights: value.highlights,
        heroImage: value.heroImage ? candid_some(await to_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value.heroImage)) : candid_none(),
        story: value.story,
        isVerified: value.isVerified,
        category: to_candid_Category_n14(_uploadFile, _downloadFile, value.category),
        trustedHosts: value.trustedHosts
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    villageStays: null;
} | {
    culturalImmersion: null;
} | {
    foodTrails: null;
} | {
    natureEco: null;
} {
    return value == Category.villageStays ? {
        villageStays: null
    } : value == Category.culturalImmersion ? {
        culturalImmersion: null
    } : value == Category.foodTrails ? {
        foodTrails: null
    } : value == Category.natureEco ? {
        natureEco: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaType): {
    story: null;
} | {
    gallery: null;
} {
    return value == MediaType.story ? {
        story: null
    } : value == MediaType.gallery ? {
        gallery: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    host: null;
} | {
    traveller: null;
} {
    return value == UserRole.host ? {
        host: null
    } : value == UserRole.traveller ? {
        traveller: null
    } : value;
}
async function to_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n13(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
